### ISSUE TITLE
obs2ioda fails to process himawari HSD data

### ISSUE THREAD

**Issue by mrixlam** [NCAR/obs2ioda#7]
I tried to read and convert HSD binary data for himawari 8 (available here: /glade/derecho/scratch/mrislam/work/pandac/radiance_data_processing/obs_ioda/work/input) but it did not work as expected. 

I used the following command: "./obs2ioda-v2.x -i input/ -ahi -t 201801010000", as suggested by the readme file: https://github.com/jamiebresch/obs2ioda/blob/main/obs2ioda-v2/README.md. 

I tried both the obs2ioda.x (from obs2ioda-v1) and obs2ioda-v2.x (from obs2ioda-v2) built in the following directory (/glade/derecho/scratch/mrislam/work/pandac/radiance_data_processing/obs2ioda) gave me the exact same error message. 

forrtl: severe (71): integer divide by zero
Image              PC                Routine            Line        Source             
libpthread-2.31.s  000014FA32DF28C0  Unknown               Unknown  Unknown
obs2ioda-v2.x      0000000000411605  Unknown               Unknown  Unknown
obs2ioda-v2.x      000000000041F659  Unknown               Unknown  Unknown
obs2ioda-v2.x      0000000000402C8D  Unknown               Unknown  Unknown
libc-2.31.so       000014FA32A1C29D  __libc_start_main     Unknown  Unknown
obs2ioda-v2.x      0000000000402BBA  Unknown               Unknown  Unknown

Screenshot: 
<img width="731" alt="Screenshot 2024-06-04 at 7 27 37 AM" src="https://github.com/NCAR/obs2ioda/assets/97724970/1751b1fe-6dba-4bd9-8cf4-3b44b395a1a1">

**Comment by byoung-joo** [comment]
Hi @mrixlam ,

Please add `-s 1` (subsampling) to your command OR use the recently (?) added superobbing options recently (?) added (https://github.com/NCAR/obs2ioda/pull/4).

**Comment by mrixlam** [comment]
Hi @byoung-joo thanks for looking into this issue. 

With subsampling, the command works and I was able to generate a HDF formatted data. Since the use of subsampling option is required, I suggest that we remove the following sentence from obs2ioda's [readme.md](https://github.com/jamiebresch/obs2ioda/blob/main/obs2ioda-v2/README.md) file: 

"Number of pixels to skip is optional."

**Comment by byoung-joo** [comment]
> Since the use of subsampling option is required, I suggest that we remove the following sentence from obs2ioda's [readme.md](https://github.com/jamiebresch/obs2ioda/blob/main/obs2ioda-v2/README.md) file:
>
> "Number of pixels to skip is optional."

@mrixlam , please open a PR here when you are ready.  
I think this repository is a right place.  Can you confirm this, @ibanos90 ?

**Comment by ibanos90** [comment]
> > Since the use of subsampling option is required, I suggest that we remove the following sentence from obs2ioda's [readme.md](https://github.com/jamiebresch/obs2ioda/blob/main/obs2ioda-v2/README.md) file:
> > "Number of pixels to skip is optional."
> 
> @mrixlam , please open a PR here when you are ready. I think this repository is a right place. Can you confirm this, @ibanos90 ?

Yes, here is the right place. Thanks @byoung-joo for looking into this! I thought this variable had a default value (i.e., 1 for no skipping any value), which may be better in this case. By doing that, we can keep the comment in the Readme but specify this value in the script. What do you think @byoung-joo?

**Comment by byoung-joo** [comment]
I agree, that (setting the default value of 1  for subsample)would work, too!

**Comment by mrixlam** [comment]
Okay, I will open a PR for this modification. Thanks @ibanos90 and @byoung-joo for your help in fixing this issue for me, and future users.
